### ISSUE TITLE
shuabu登入不了

### ISSUE THREAD

**Issue by caiweidong1987** [wdvipa/shuabu#1]
显示登入失败 200
![失败了2](https://github.com/wdvipa/shuabu/assets/68548193/b893b870-cdbf-4623-8a23-67e6f54ba0b0)

**Comment by wdvipa** [comment]
登录失败前面没字了？
> 显示登入失败 200 ![失败了2](https://private-user-images.githubusercontent.com/68548193/301048912-b893b870-cdbf-4623-8a23-67e6f54ba0b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTY1MTYsIm5iZiI6MTcwNjY5NjIxNiwicGF0aCI6Ii82ODU0ODE5My8zMDEwNDg5MTItYjg5M2I4NzAtY2RiZi00NjIzLThhMjMtNjdlNmY1NGJhMGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZmFjM2YzNjU1NTdmNTc4OGQ3MGZjYzg4YTg3Y2ExZWUyZDc1MDFiZjRhYjg3Y2QxNTBmNTdmOWFkZWNiODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SAaQ2og2MH-ima63Lw3NgG3etUzKisgQj2dVT9mO4AA)

**Comment by wdvipa** [comment]
脚本自测没问题

**Comment by caiweidong1987** [comment]
![刷步数](https://github.com/wdvipa/shuabu/assets/68548193/3ad55734-6574-4cd2-8f12-ae5a3b0d6fb1)
就这样呢。。

**Comment by wdvipa** [comment]
> ![刷步数](https://private-user-images.githubusercontent.com/68548193/301714040-3ad55734-6574-4cd2-8f12-ae5a3b0d6fb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDM1MjMsIm5iZiI6MTcwNjg0MzIyMywicGF0aCI6Ii82ODU0ODE5My8zMDE3MTQwNDAtM2FkNTU3MzQtNjU3NC00Y2QyLThmMTItYWU1YTNiMGQ2ZmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAzMDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YjcwYzcwN2Y4ODY3NTI0NWMwOWE0NWVmOGQxMjMxNWM0NGVjOTk4OTgzYWU5ZjFmOTVjZWYwZWI4NzUyYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3nc-ZRmyRel0v5Lxw9li215ZnqlNUgAMiLAdDYh_2VE) 就这样呢。。

登录失败不清楚，我问了好几个人都没问题，看看账号密码问题，现在是app_token接口炸了，没新接口hhh

**Comment by caiweidong1987** [comment]
我帐号密码手动登入那个app 显示是可以的呢。。

**Comment by wdvipa** [comment]
> 我帐号密码手动登入那个app 显示是可以的呢。。

主要是我在问了好几个都可以，我也尝试不出你的状况，按理来说密码错误会提示密码错误直接不跑的
